Added option page to select linkStyle
brunoluiz/grammarly-markdown-extension pull request #13
Opened 2020-10-21 07:48 UTC by gianarb

I would like to change the linkStyle. Previously it was fixed to
referenced but very often I want the inline version of it.

This PR drafts an options page that contains a select box to pick the one
you prefer an end-user.

Fixed #12

Thanks a lot for this plugin, easy and cool!

2020-10-21 19:21 UTC, brunoluiz requested changes
Thanks for contributing! I was thinking about adding a configuration pages last week -- You read my mind 😅

Amazing job overall 🙌 I left some suggested changes on the PR and probably I will get some time to test it later this week.

2020-10-21 19:21 UTC, brunoluiz commented on src/options.html
> +        <label for="turndown-linkSyle">Choose a car:</label>
```suggestion
        <label for="turndown-linkSyle">Choose link style:</label>
```

2020-10-21 19:21 UTC, brunoluiz commented on src/js/options.js
> +function save_options() {
Just to be consistent with the rest of the code (probably will need adjustments where it is referenced)

```suggestion
const saveOptions = () => {
```

2020-10-21 19:21 UTC, brunoluiz commented on src/js/options.js
> +function restore_options() {
Just to be consistent with the rest of the code (probably will need adjustments where it is referenced)
```suggestion
const restoreOptions = () => {
```

2020-10-21 19:21 UTC, brunoluiz commented on src/js/options.js
> +  // Use default value color = 'red' and likesColor = true.
```suggestion
```

2020-10-21 19:21 UTC, brunoluiz commented on src/js/options.js
> +  }, function(items) {
```suggestion
  }, (items) => {
```

2020-10-21 19:21 UTC, brunoluiz commented on src/js/popup.js
> +        var turndownService = new TurndownService(items);
```suggestion
    }, (items) => {
        const turndownService = new TurndownService(items);
```

2020-10-21 19:21 UTC, brunoluiz commented on src/js/popup.js
> +
```suggestion
```

2020-10-21 19:21 UTC, brunoluiz commented on src/js/popup.js
> +
Usually I try to avoid having too much spacing between sections.

```suggestion
```

2020-10-21 19:21 UTC, brunoluiz commented on src/js/options.js
> +document.getElementById('save').addEventListener('click', save_options);
```suggestion
document.getElementById('save').addEventListener('click', saveOptions);
```

2020-10-21 19:21 UTC, brunoluiz commented on src/js/options.js
> +document.addEventListener('DOMContentLoaded', restore_options);
```suggestion
document.addEventListener('DOMContentLoaded', restoreOptions);
```

2020-10-21 19:21 UTC, brunoluiz commented on src/js/options.js
> +  var linkStyle = document.getElementById('turndown-linkSyle').value;
```suggestion
  const linkStyle = document.getElementById('turndown-linkSyle').value;
```

2020-10-21 19:23 UTC, brunoluiz commented
By the way, I am not sure why CircleCI didn't run tests/linter on your pull request. Mind running it manually? `npm run lint` should do 😉

2020-10-23 08:18 UTC, gianarb commented
Updated. Thanks for your review @brunoluiz ! I am not fluent in Javascript as you can imagine, but the `lint` is green now and I am using this version of the extension currently, it works well.

2020-10-23 09:59 UTC, brunoluiz approved these changes

2020-10-23 10:00 UTC, merged

2020-10-23 10:00 UTC, brunoluiz commented
Will prepare a release soon 😉